package main.java.UI.MainFace;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import main.java.Entity.Database;
import main.java.UI.AddNewCar;

/**
 *
 * @author admin
 */
public class AdminFace extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminFace() {
        initComponents();
        loadCarData(); // Tải dữ liệu khi khởi tạo giao diện
        loadUserData();
    }

    
    class jPanelGradient extends JPanel {
        protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        Color color1 = new Color(100,57,255);
        Color color2 = new Color(124,245,255);
        int width = getWidth();
        int height = getHeight();
        GradientPaint gradientPaint = new GradientPaint(0, 0, color1, 0 , height, color2);
        g2d.setPaint(gradientPaint);
        g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewAdminDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        emailLoginButton = new javax.swing.JLabel();
        emailLoginButton2 = new javax.swing.JLabel();
        emailLoginButton3 = new javax.swing.JLabel();
        emailLoginButton4 = new javax.swing.JLabel();
        firstNameAddNewAdminTextField = new javax.swing.JTextField();
        emailAddNewAdminTextField = new javax.swing.JTextField();
        phoneNumAddNewAdminTextField = new javax.swing.JTextField();
        confirmPassAddNewAdminTextField = new javax.swing.JTextField();
        passAddNewAdminTextField = new javax.swing.JTextField();
        cancelAddNewAdminrButton = new javax.swing.JButton();
        addAddNewAdminButton = new javax.swing.JButton();
        emailLoginButton21 = new javax.swing.JLabel();
        lastNameAddNewAdminTextField = new javax.swing.JTextField();
        emailLoginButton22 = new javax.swing.JLabel();
        updateCarDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        emailLoginButton7 = new javax.swing.JLabel();
        emailLoginButton8 = new javax.swing.JLabel();
        emailLoginButton9 = new javax.swing.JLabel();
        emailLoginButton10 = new javax.swing.JLabel();
        emailLoginButton11 = new javax.swing.JLabel();
        emailLoginButton12 = new javax.swing.JLabel();
        emailLoginButton13 = new javax.swing.JLabel();
        newIdAddNewCarTextField1 = new javax.swing.JTextField();
        NewBrandAddNewCarTextField1 = new javax.swing.JTextField();
        NewColourAddNewCarTextField1 = new javax.swing.JTextField();
        NewModelAddNewCarTextField1 = new javax.swing.JTextField();
        NewPriceAddNewCarTextField1 = new javax.swing.JTextField();
        NewNumberAddNewCarTextField1 = new javax.swing.JTextField();
        NewYearAddNewCarTextField1 = new javax.swing.JTextField();
        cancelUpdateCarButton = new javax.swing.JButton();
        updateUpdateCarButton = new javax.swing.JButton();
        showUserBuyDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        addNewCarDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        emailLoginButton14 = new javax.swing.JLabel();
        emailLoginButton15 = new javax.swing.JLabel();
        emailLoginButton16 = new javax.swing.JLabel();
        emailLoginButton17 = new javax.swing.JLabel();
        emailLoginButton18 = new javax.swing.JLabel();
        emailLoginButton19 = new javax.swing.JLabel();
        emailLoginButton20 = new javax.swing.JLabel();
        idAddNewCarTextField = new javax.swing.JTextField();
        brandAddNewCarTextField = new javax.swing.JTextField();
        colourAddNewCarTextField = new javax.swing.JTextField();
        modelAddNewCarTextField = new javax.swing.JTextField();
        priceAddNewCarTextField = new javax.swing.JTextField();
        numberAddNewCarTextField = new javax.swing.JTextField();
        yearAddNewCarTextField = new javax.swing.JTextField();
        cancelAddNewCarButton = new javax.swing.JButton();
        addAddNewCarButton = new javax.swing.JButton();
        bigContainer = new jPanelGradient();
        sideBar = new javax.swing.JPanel();
        sideBarLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuItemPanel = new jPanelGradient();
        addNewCarButton = new javax.swing.JButton();
        updateNewCarButton = new javax.swing.JButton();
        deleteCarButton = new javax.swing.JButton();
        addNewAdminButton = new javax.swing.JButton();
        viewAllUserButton = new javax.swing.JButton();
        showUserBuyButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        changePassButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();

        addNewAdminDialog.setTitle("Add New Admin");
        addNewAdminDialog.setBackground(new java.awt.Color(255, 255, 255));
        addNewAdminDialog.setMinimumSize(new java.awt.Dimension(640, 400));
        addNewAdminDialog.setModal(true);
        addNewAdminDialog.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(54, 171, 239));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add New Admin");

        emailLoginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton.setText("First Name");

        emailLoginButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton2.setText("Phone Number");

        emailLoginButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton3.setText("Email");

        emailLoginButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton4.setText("Password");

        firstNameAddNewAdminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameAddNewAdminTextFieldActionPerformed(evt);
            }
        });

        cancelAddNewAdminrButton.setBackground(new java.awt.Color(54, 171, 239));
        cancelAddNewAdminrButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelAddNewAdminrButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelAddNewAdminrButton.setText("Cancel");
        cancelAddNewAdminrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddNewAdminrButtonActionPerformed(evt);
            }
        });

        addAddNewAdminButton.setBackground(new java.awt.Color(54, 171, 239));
        addAddNewAdminButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addAddNewAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        addAddNewAdminButton.setText("Add");
        addAddNewAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddNewAdminButtonActionPerformed(evt);
            }
        });

        emailLoginButton21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton21.setText("Last Name");

        lastNameAddNewAdminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameAddNewAdminTextFieldActionPerformed(evt);
            }
        });

        emailLoginButton22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton22.setText("Confirm Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(emailLoginButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstNameAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailLoginButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNameAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelAddNewAdminrButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addAddNewAdminButton))
                    .addComponent(phoneNumAddNewAdminTextField)
                    .addComponent(emailAddNewAdminTextField)
                    .addComponent(passAddNewAdminTextField)
                    .addComponent(confirmPassAddNewAdminTextField))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailLoginButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLoginButton2)
                            .addComponent(phoneNumAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLoginButton3)
                            .addComponent(emailAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLoginButton4)
                            .addComponent(passAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailLoginButton21)
                        .addComponent(lastNameAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLoginButton22))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAddNewAdminrButton)
                    .addComponent(addAddNewAdminButton))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addNewAdminDialogLayout = new javax.swing.GroupLayout(addNewAdminDialog.getContentPane());
        addNewAdminDialog.getContentPane().setLayout(addNewAdminDialogLayout);
        addNewAdminDialogLayout.setHorizontalGroup(
            addNewAdminDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addNewAdminDialogLayout.setVerticalGroup(
            addNewAdminDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        updateCarDialog.setTitle("Update Car");
        updateCarDialog.setBackground(new java.awt.Color(255, 255, 255));
        updateCarDialog.setMinimumSize(new java.awt.Dimension(640, 400));
        updateCarDialog.setModal(true);
        updateCarDialog.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(54, 171, 239));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Update Car");

        emailLoginButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton7.setText("New ID");

        emailLoginButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton8.setText("New Brand");

        emailLoginButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton9.setText("New Model");

        emailLoginButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton10.setText("New Colour");

        emailLoginButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton11.setText("New Year of Manufacture");

        emailLoginButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton12.setText("New Price");

        emailLoginButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton13.setText("New Current Number");

        newIdAddNewCarTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newIdAddNewCarTextField1ActionPerformed(evt);
            }
        });

        cancelUpdateCarButton.setBackground(new java.awt.Color(54, 171, 239));
        cancelUpdateCarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelUpdateCarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelUpdateCarButton.setText("Cancel");
        cancelUpdateCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUpdateCarButtonActionPerformed(evt);
            }
        });

        updateUpdateCarButton.setBackground(new java.awt.Color(54, 171, 239));
        updateUpdateCarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateUpdateCarButton.setForeground(new java.awt.Color(255, 255, 255));
        updateUpdateCarButton.setText("Update");
        updateUpdateCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUpdateCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailLoginButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLoginButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewBrandAddNewCarTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewModelAddNewCarTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewColourAddNewCarTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewYearAddNewCarTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPriceAddNewCarTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(cancelUpdateCarButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateUpdateCarButton))
                        .addComponent(NewNumberAddNewCarTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(newIdAddNewCarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton7)
                    .addComponent(newIdAddNewCarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton8)
                    .addComponent(NewBrandAddNewCarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton9)
                    .addComponent(NewModelAddNewCarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton10)
                    .addComponent(NewColourAddNewCarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton11)
                    .addComponent(NewYearAddNewCarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton12)
                    .addComponent(NewPriceAddNewCarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton13)
                    .addComponent(NewNumberAddNewCarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelUpdateCarButton)
                    .addComponent(updateUpdateCarButton))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout updateCarDialogLayout = new javax.swing.GroupLayout(updateCarDialog.getContentPane());
        updateCarDialog.getContentPane().setLayout(updateCarDialogLayout);
        updateCarDialogLayout.setHorizontalGroup(
            updateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updateCarDialogLayout.setVerticalGroup(
            updateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        showUserBuyDialog.setMinimumSize(new java.awt.Dimension(640, 400));
        showUserBuyDialog.setModal(true);
        showUserBuyDialog.setResizable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout showUserBuyDialogLayout = new javax.swing.GroupLayout(showUserBuyDialog.getContentPane());
        showUserBuyDialog.getContentPane().setLayout(showUserBuyDialogLayout);
        showUserBuyDialogLayout.setHorizontalGroup(
            showUserBuyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        showUserBuyDialogLayout.setVerticalGroup(
            showUserBuyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addNewCarDialog.setTitle("Add New Admin");
        addNewCarDialog.setBackground(new java.awt.Color(255, 255, 255));
        addNewCarDialog.setMinimumSize(new java.awt.Dimension(640, 400));
        addNewCarDialog.setModal(true);
        addNewCarDialog.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(54, 171, 239));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add New Car");

        emailLoginButton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton14.setText("ID");

        emailLoginButton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton15.setText("Brand");

        emailLoginButton16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton16.setText("Model");

        emailLoginButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton17.setText("Colour");

        emailLoginButton18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton18.setText("Year of Manufacture");

        emailLoginButton19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton19.setText("Price");

        emailLoginButton20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLoginButton20.setText("Current Number");

        idAddNewCarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAddNewCarTextFieldActionPerformed(evt);
            }
        });

        brandAddNewCarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandAddNewCarTextFieldActionPerformed(evt);
            }
        });

        cancelAddNewCarButton.setBackground(new java.awt.Color(54, 171, 239));
        cancelAddNewCarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelAddNewCarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelAddNewCarButton.setText("Cancel");
        cancelAddNewCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddNewCarButtonActionPerformed(evt);
            }
        });

        addAddNewCarButton.setBackground(new java.awt.Color(54, 171, 239));
        addAddNewCarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addAddNewCarButton.setForeground(new java.awt.Color(255, 255, 255));
        addAddNewCarButton.setText("Add");
        addAddNewCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddNewCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLoginButton15)
                            .addComponent(emailLoginButton14)
                            .addComponent(emailLoginButton16)
                            .addComponent(emailLoginButton17))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLoginButton19)
                            .addComponent(emailLoginButton18)
                            .addComponent(emailLoginButton20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(idAddNewCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(brandAddNewCarTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelAddNewCarTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colourAddNewCarTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearAddNewCarTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceAddNewCarTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(cancelAddNewCarButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAddNewCarButton))
                        .addComponent(numberAddNewCarTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton14)
                    .addComponent(idAddNewCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton15)
                    .addComponent(brandAddNewCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton16)
                    .addComponent(modelAddNewCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton17)
                    .addComponent(colourAddNewCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton18)
                    .addComponent(yearAddNewCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton19)
                    .addComponent(priceAddNewCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLoginButton20)
                    .addComponent(numberAddNewCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAddNewCarButton)
                    .addComponent(addAddNewCarButton))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout addNewCarDialogLayout = new javax.swing.GroupLayout(addNewCarDialog.getContentPane());
        addNewCarDialog.getContentPane().setLayout(addNewCarDialogLayout);
        addNewCarDialogLayout.setHorizontalGroup(
            addNewCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addNewCarDialogLayout.setVerticalGroup(
            addNewCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wheel Finder Admin");
        setResizable(false);

        sideBar.setBackground(new java.awt.Color(54, 171, 239));
        sideBar.setAlignmentX(0.0F);
        sideBar.setAlignmentY(0.0F);

        sideBarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/UI/logo/logoandtext100.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("nocopyright @ CLC04");

        addNewCarButton.setBackground(new java.awt.Color(54, 171, 239));
        addNewCarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addNewCarButton.setForeground(new java.awt.Color(255, 255, 255));
        addNewCarButton.setText("Add New Car");
        addNewCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCarButtonActionPerformed(evt);
            }
        });

        updateNewCarButton.setBackground(new java.awt.Color(54, 171, 239));
        updateNewCarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateNewCarButton.setForeground(new java.awt.Color(255, 255, 255));
        updateNewCarButton.setText("Update New Car");
        updateNewCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNewCarButtonActionPerformed(evt);
            }
        });

        deleteCarButton.setBackground(new java.awt.Color(54, 171, 239));
        deleteCarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteCarButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteCarButton.setText("Delete New Car");
        deleteCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCarButtonActionPerformed(evt);
            }
        });

        addNewAdminButton.setBackground(new java.awt.Color(54, 171, 239));
        addNewAdminButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addNewAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        addNewAdminButton.setText("Add New Admin");
        addNewAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewAdminButtonActionPerformed(evt);
            }
        });

        viewAllUserButton.setBackground(new java.awt.Color(54, 171, 239));
        viewAllUserButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        viewAllUserButton.setForeground(new java.awt.Color(255, 255, 255));
        viewAllUserButton.setText("View All Users");
        viewAllUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllUserButtonActionPerformed(evt);
            }
        });

        showUserBuyButton.setBackground(new java.awt.Color(54, 171, 239));
        showUserBuyButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showUserBuyButton.setForeground(new java.awt.Color(255, 255, 255));
        showUserBuyButton.setText("Show User's Buy");
        showUserBuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUserBuyButtonActionPerformed(evt);
            }
        });

        deleteUserButton.setBackground(new java.awt.Color(54, 171, 239));
        deleteUserButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteUserButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteUserButton.setText("Delete User");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        logOutButton.setBackground(new java.awt.Color(54, 171, 239));
        logOutButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        changePassButton.setBackground(new java.awt.Color(54, 171, 239));
        changePassButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        changePassButton.setForeground(new java.awt.Color(255, 255, 255));
        changePassButton.setText("Change Password");
        changePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuItemPanelLayout = new javax.swing.GroupLayout(menuItemPanel);
        menuItemPanel.setLayout(menuItemPanelLayout);
        menuItemPanelLayout.setHorizontalGroup(
            menuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateNewCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addNewAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewAllUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showUserBuyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuItemPanelLayout.setVerticalGroup(
            menuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewCarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateNewCarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteCarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewAdminButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAllUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showUserBuyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changePassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOutButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(sideBarLogo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuItemPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideBarLogo)
                .addGap(18, 18, 18)
                .addComponent(menuItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Brand", "Model", "Colour", "Year Realease", "Price", "Aivailable"
            }
        ));
        jScrollPane3.setViewportView(carTable);

        javax.swing.GroupLayout bigContainerLayout = new javax.swing.GroupLayout(bigContainer);
        bigContainer.setLayout(bigContainerLayout);
        bigContainerLayout.setHorizontalGroup(
            bigContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bigContainerLayout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addContainerGap())
        );
        bigContainerLayout.setVerticalGroup(
            bigContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bigContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bigContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bigContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1134, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelAddNewAdminrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddNewAdminrButtonActionPerformed
        // TODO add your handling code here:
        addNewAdminDialog.setVisible(false);
    }//GEN-LAST:event_cancelAddNewAdminrButtonActionPerformed

    private void addAddNewAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddNewAdminButtonActionPerformed
        // TODO add your handling code here:
        addNewAdminDialog.setVisible(false);
    }//GEN-LAST:event_addAddNewAdminButtonActionPerformed

    private void firstNameAddNewAdminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameAddNewAdminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameAddNewAdminTextFieldActionPerformed

    private void newIdAddNewCarTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newIdAddNewCarTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newIdAddNewCarTextField1ActionPerformed

    private void cancelUpdateCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUpdateCarButtonActionPerformed
        // TODO add your handling code here:
        updateCarDialog.setVisible(false);
    }//GEN-LAST:event_cancelUpdateCarButtonActionPerformed

    private void updateUpdateCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUpdateCarButtonActionPerformed
        // TODO add your handling code here:
        updateCarDialog.setVisible(false);
    }//GEN-LAST:event_updateUpdateCarButtonActionPerformed

    private void idAddNewCarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAddNewCarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAddNewCarTextFieldActionPerformed

    private void cancelAddNewCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddNewCarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelAddNewCarButtonActionPerformed

    private void addAddNewCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddNewCarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAddNewCarButtonActionPerformed

    private void lastNameAddNewAdminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameAddNewAdminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameAddNewAdminTextFieldActionPerformed

    private void brandAddNewCarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandAddNewCarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandAddNewCarTextFieldActionPerformed

    private void addNewCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCarButtonActionPerformed
        // TODO add your handling code here:
        AddNewCar AddNewCar = new AddNewCar();
        AddNewCar.setVisible(true);
    }//GEN-LAST:event_addNewCarButtonActionPerformed

    private void updateNewCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNewCarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateNewCarButtonActionPerformed

    private void deleteCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCarButtonActionPerformed

    private void addNewAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewAdminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewAdminButtonActionPerformed

    private void viewAllUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewAllUserButtonActionPerformed

    private void showUserBuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUserBuyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showUserBuyButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void changePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changePassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFace().setVisible(true);
            }
        });
    }
    public void loadCarData() {
    try (Database db = new Database()) { // Sử dụng try-with-resources để tự động đóng kết nối
        Connection conn = db.getConnection(); // Lấy kết nối từ class Database
        if (conn == null) {
            System.out.println("Không thể kết nối đến cơ sở dữ liệu!");
            return;
        }

        String query = "SELECT id, brand, model, color, yearRelease, price, available FROM car";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        // Lấy mô hình bảng và xóa dữ liệu cũ
        DefaultTableModel tableModel = (DefaultTableModel) viewCarTable.getModel();
        tableModel.setRowCount(0);

        // Thêm dữ liệu mới vào bảng
        while (rs.next()) {
            Object[] row = new Object[7];
            row[0] = rs.getInt("id");
            row[1] = rs.getString("brand");
            row[2] = rs.getString("model");
            row[3] = rs.getString("color");
            row[4] = rs.getInt("yearRelease"); // Chỉnh sửa lại tên cột chính xác
            row[5] = rs.getDouble("price");
            row[6] = rs.getInt("available");
            tableModel.addRow(row);
        }

        rs.close();
        stmt.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
public void loadUserData() {
    try (Database db = new Database()) { // Sử dụng try-with-resources để tự động đóng kết nối
        Connection conn = db.getConnection(); // Lấy kết nối từ class Database
        if (conn == null) {
            System.out.println("Không thể kết nối đến cơ sở dữ liệu!");
            return;
        }

        String query = "SELECT id, firstName, lastName, email, phoneNum FROM user"; // Truy vấn để lấy dữ liệu người dùng
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        // Lấy mô hình bảng và xóa dữ liệu cũ
        DefaultTableModel tableModel = (DefaultTableModel) viewUserTable.getModel();
        tableModel.setRowCount(0);

        // Thêm dữ liệu mới vào bảng
        while (rs.next()) {
            Object[] row = new Object[5]; // Cột tương ứng với 7 trường trong bảng người dùng
            row[0] = rs.getInt("id");
            row[1] = rs.getString("firstName");
            row[2] = rs.getString("lastName");
            row[3] = rs.getString("email");
            row[4] = rs.getString("phoneNum");
            tableModel.addRow(row);
        }

        rs.close();
        stmt.close();
    } catch (Exception e) {
        e.printStackTrace();
    }

}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NewBrandAddNewCarTextField1;
    private javax.swing.JTextField NewColourAddNewCarTextField1;
    private javax.swing.JTextField NewModelAddNewCarTextField1;
    private javax.swing.JTextField NewNumberAddNewCarTextField1;
    private javax.swing.JTextField NewPriceAddNewCarTextField1;
    private javax.swing.JTextField NewYearAddNewCarTextField1;
    private javax.swing.JButton addAddNewAdminButton;
    private javax.swing.JButton addAddNewCarButton;
    private javax.swing.JButton addNewAdminButton;
    private javax.swing.JDialog addNewAdminDialog;
    private javax.swing.JButton addNewCarButton;
    private javax.swing.JDialog addNewCarDialog;
    private javax.swing.JPanel bigContainer;
    private javax.swing.JTextField brandAddNewCarTextField;
    private javax.swing.JButton cancelAddNewAdminrButton;
    private javax.swing.JButton cancelAddNewCarButton;
    private javax.swing.JButton cancelUpdateCarButton;
    private javax.swing.JTable carTable;
    private javax.swing.JButton changePassButton;
    private javax.swing.JTextField colourAddNewCarTextField;
    private javax.swing.JTextField confirmPassAddNewAdminTextField;
    private javax.swing.JButton deleteCarButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JTextField emailAddNewAdminTextField;
    private javax.swing.JLabel emailLoginButton;
    private javax.swing.JLabel emailLoginButton10;
    private javax.swing.JLabel emailLoginButton11;
    private javax.swing.JLabel emailLoginButton12;
    private javax.swing.JLabel emailLoginButton13;
    private javax.swing.JLabel emailLoginButton14;
    private javax.swing.JLabel emailLoginButton15;
    private javax.swing.JLabel emailLoginButton16;
    private javax.swing.JLabel emailLoginButton17;
    private javax.swing.JLabel emailLoginButton18;
    private javax.swing.JLabel emailLoginButton19;
    private javax.swing.JLabel emailLoginButton2;
    private javax.swing.JLabel emailLoginButton20;
    private javax.swing.JLabel emailLoginButton21;
    private javax.swing.JLabel emailLoginButton22;
    private javax.swing.JLabel emailLoginButton3;
    private javax.swing.JLabel emailLoginButton4;
    private javax.swing.JLabel emailLoginButton7;
    private javax.swing.JLabel emailLoginButton8;
    private javax.swing.JLabel emailLoginButton9;
    private javax.swing.JTextField firstNameAddNewAdminTextField;
    private javax.swing.JTextField idAddNewCarTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameAddNewAdminTextField;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel menuItemPanel;
    private javax.swing.JTextField modelAddNewCarTextField;
    private javax.swing.JTextField newIdAddNewCarTextField1;
    private javax.swing.JTextField numberAddNewCarTextField;
    private javax.swing.JTextField passAddNewAdminTextField;
    private javax.swing.JTextField phoneNumAddNewAdminTextField;
    private javax.swing.JTextField priceAddNewCarTextField;
    private javax.swing.JButton showUserBuyButton;
    private javax.swing.JDialog showUserBuyDialog;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel sideBarLogo;
    private javax.swing.JDialog updateCarDialog;
    private javax.swing.JButton updateNewCarButton;
    private javax.swing.JButton updateUpdateCarButton;
    private javax.swing.JButton viewAllUserButton;
    private javax.swing.JTextField yearAddNewCarTextField;
    // End of variables declaration//GEN-END:variables
}
